"""Gemini AI client for FinGuard AI — grounded financial analysis."""

import json
import logging
from datetime import datetime, timezone
from typing import Any

try:
    import google.generativeai as genai
    GENAI_AVAILABLE = True
except ImportError:
    genai = None
    GENAI_AVAILABLE = False

from app.config.settings import settings
from app.schemas.ai import AIResponse, EvidenceItem, ExecutiveBriefResponse

logger = logging.getLogger(__name__)

# Configure Gemini on module load if key is set — key is read from settings only, never logged.
if GENAI_AVAILABLE and settings.gemini_api_key:
    try:
        genai.configure(api_key=settings.gemini_api_key)
    except Exception as e:
        logger.warning("Could not initialize genai with provided key: %s", e)

GEMINI_MODEL = "gemini-1.5-flash"


SYSTEM_PROMPT = """
You are FinGuard AI's Executive Financial Analyst — an analytical assistant that helps executives understand their financial data.

GROUNDING CONTRACT — you MUST follow these rules without exception:

1. USE ONLY the verified financial metrics provided in the context. Never invent, estimate, or extrapolate numbers not provided.
2. If a metric is not available in the context, explicitly state it is not available. Do not fabricate it.
3. Clearly distinguish FACT (from the data) from INTERPRETATION (your analytical reasoning).
4. Do not claim causation unless the data directly supports it. Use language like "one possible contributor" or "the data suggests".
5. Do not present forecasts as certainty. Always note that forecasts are statistical estimates.
6. Do not label any transaction, expense, or pattern as "fraud" unless the context explicitly provides validated fraud labels.
7. Use language such as "requires investigation", "potential anomaly detected", "management should consider reviewing".
8. Do not give regulated financial or investment advice.
9. Always reference the specific metric or data source when making a claim.
10. Acknowledge uncertainty and limitations where applicable.

Language guidelines:
- Use "Based on the available data..."
- Use "One possible contributor is..."
- Use "The data indicates..."
- Use "This should be investigated..."
- Use "According to the verified analytics..."
- NEVER use "guaranteed", "certain", "definitely fraud", "invest immediately", "will definitely"

Your responses must be structured, concise, and executive-friendly.
Avoid jargon overload. Explain financial terms when needed for a non-technical executive.
"""

_DISCLAIMER = (
    "This executive brief is generated by AI based on verified financial analytics. "
    "It is a decision-support tool and does not constitute regulated financial advice."
)


class GeminiClient:
    """Wraps the Gemini generative model with grounded financial prompting."""

    def __init__(self) -> None:
        if GENAI_AVAILABLE and settings.gemini_api_key:
            try:
                self.model = genai.GenerativeModel(
                    model_name=GEMINI_MODEL,
                    system_instruction=SYSTEM_PROMPT,
                )
            except Exception as e:
                logger.warning("Failed to instantiate GenerativeModel: %s", e)
                self.model = None
        else:
            self.model = None


    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _format_context_for_prompt(self, context: dict) -> str:
        """Convert context dict to a clean, token-efficient string for the prompt.

        Targets ~2 000 tokens. Raw JSON dumps are avoided in favour of labelled
        key-value blocks so the model can parse them reliably.
        """
        lines: list[str] = []

        lines.append(f"ANALYSIS PERIOD : {context.get('period', 'N/A')}")
        lines.append(f"AS OF DATE      : {context.get('as_of_date', 'N/A')}")
        lines.append(f"DATA SOURCE     : {context.get('data_note', 'N/A')}")

        # KPIs
        kpis: dict = context.get("kpis", {})
        if kpis:
            lines.append("\n--- KEY PERFORMANCE INDICATORS ---")
            lines.append(f"Revenue              : ${kpis.get('revenue', {}).get('value', 'N/A'):,}  (prev: ${kpis.get('revenue', {}).get('previous', 'N/A'):,})")
            lines.append(f"Net Profit           : ${kpis.get('net_profit', {}).get('value', 'N/A'):,}  (prev: ${kpis.get('net_profit', {}).get('previous', 'N/A'):,})")
            lines.append(f"Gross Margin         : {kpis.get('gross_margin_pct', 'N/A')}%")
            lines.append(f"Net Margin           : {kpis.get('net_margin_pct', 'N/A')}%")
            lines.append(f"Total Expenses       : ${kpis.get('total_expenses', 'N/A'):,}")
            lines.append(f"Net Cash Flow        : ${kpis.get('net_cash_flow', 'N/A'):,}")
            lines.append(f"Revenue Growth       : {kpis.get('revenue_growth_pct', 'N/A')}%")
            lines.append(f"Outstanding Receivables: ${kpis.get('outstanding_receivables', 'N/A'):,}")

        # Budget summary
        budget: dict = context.get("budget_summary", {})
        if budget:
            lines.append("\n--- BUDGET SUMMARY ---")
            lines.append(f"Year                 : {budget.get('year', 'N/A')}")
            lines.append(f"Overspending Areas   : {budget.get('overspending_count', 'N/A')}")
            lines.append(f"Underutilised Areas  : {budget.get('underutilized_count', 'N/A')}")
            for overrun in budget.get("top_overruns", []):
                lines.append(
                    f"  Overrun — {overrun.get('category', '?')} / {overrun.get('department', '?')}: "
                    f"{overrun.get('variance_pct', '?')}% over budget"
                )

        # Receivables
        rec: dict = context.get("receivables_summary", {})
        if rec:
            lines.append("\n--- RECEIVABLES AGING ---")
            for key, val in rec.items():
                lines.append(f"  {key}: {val}")

        # Anomaly summary
        anomaly: dict = context.get("anomaly_summary", {})
        if anomaly:
            lines.append("\n--- ANOMALY SUMMARY ---")
            for key, val in anomaly.items():
                lines.append(f"  {key}: {val}")

        # Top expense categories
        top_exp: list = context.get("top_expense_categories", [])
        if top_exp:
            lines.append("\n--- TOP EXPENSE CATEGORIES ---")
            for cat in top_exp:
                lines.append(f"  {cat.get('category', '?')}: ${cat.get('value', 'N/A'):,}  ({cat.get('pct_of_total', 'N/A')}%)")

        # Top revenue categories
        top_rev: list = context.get("top_revenue_categories", [])
        if top_rev:
            lines.append("\n--- TOP REVENUE CATEGORIES ---")
            for cat in top_rev:
                lines.append(f"  {cat.get('category', '?')}: ${cat.get('value', 'N/A'):,}  ({cat.get('pct_of_total', 'N/A')}%)")

        # Risks (top 4 for brevity)
        risks: list = context.get("risks", [])
        if risks:
            lines.append("\n--- IDENTIFIED RISKS (top 4) ---")
            for risk in risks[:4]:
                lines.append(
                    f"  [{risk.get('severity', '?').upper()}] {risk.get('title', '?')}: "
                    f"{risk.get('description', '')}"
                )

        # Opportunities (top 4 for brevity)
        opps: list = context.get("opportunities", [])
        if opps:
            lines.append("\n--- IDENTIFIED OPPORTUNITIES (top 4) ---")
            for opp in opps[:4]:
                lines.append(f"  {opp.get('title', '?')}: {opp.get('description', '')}")

        return "\n".join(lines)

    @staticmethod
    def _now_utc() -> str:
        return datetime.now(timezone.utc).isoformat()

    @staticmethod
    def _safe_list(data: Any, key: str) -> list[str]:
        """Extract a list of strings from a parsed JSON dict, falling back to []."""
        val = data.get(key, [])
        if isinstance(val, list):
            return [str(item) for item in val]
        return []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def _extract_evidence_items(self, context: dict) -> list[EvidenceItem]:
        """Extract verified concrete metrics from financial context to display as audit evidence."""
        evidence = []
        kpis = context.get("kpis", {})
        if kpis:
            rev = kpis.get("revenue", {})
            if isinstance(rev, dict) and rev.get("value") is not None:
                evidence.append(EvidenceItem(
                    metric="Total Net Revenue",
                    value=f"${rev['value']:,.2f}",
                    source="General Ledger (Sales Invoices)",
                    context=f"Prior period: ${rev.get('previous', 0):,.2f}" if rev.get("previous") else "Historical baseline"
                ))
            prof = kpis.get("net_profit", {})
            if isinstance(prof, dict) and prof.get("value") is not None:
                evidence.append(EvidenceItem(
                    metric="Net Operating Profit",
                    value=f"${prof['value']:,.2f}",
                    source="Income Statement",
                    context=f"Net Margin: {kpis.get('net_margin_pct', 'N/A')}%"
                ))
            if kpis.get("total_expenses") is not None:
                exp_val = kpis["total_expenses"]
                val_str = f"${exp_val:,.2f}" if isinstance(exp_val, (int, float)) else str(exp_val)
                evidence.append(EvidenceItem(
                    metric="Total Operating Expenses",
                    value=val_str,
                    source="Accounts Payable Sub-ledger",
                    context="All cost centers combined"
                ))
            if kpis.get("net_cash_flow") is not None:
                cf_val = kpis["net_cash_flow"]
                val_str = f"${cf_val:,.2f}" if isinstance(cf_val, (int, float)) else str(cf_val)
                evidence.append(EvidenceItem(
                    metric="Net Cash Flow",
                    value=val_str,
                    source="Cash Flow Journal",
                    context="Operating liquidity balance"
                ))
            if kpis.get("outstanding_receivables") is not None:
                ar_val = kpis["outstanding_receivables"]
                val_str = f"${ar_val:,.2f}" if isinstance(ar_val, (int, float)) else str(ar_val)
                evidence.append(EvidenceItem(
                    metric="Outstanding Receivables",
                    value=val_str,
                    source="AR Aging Schedule",
                    context="Open invoices pending collection"
                ))

        anom = context.get("anomaly_summary", {})
        if anom and anom.get("total_anomalies") is not None:
            evidence.append(EvidenceItem(
                metric="Flagged Statistical Outliers",
                value=f"{anom['total_anomalies']} events",
                source="IQR & Z-Score Anomaly Engines",
                context=f"Critical: {anom.get('critical_count', 0)}, High: {anom.get('high_count', 0)}"
            ))

        rec = context.get("receivables_summary", {})
        if rec and (rec.get("days_61_90") or rec.get("days_over_90")):
            crit_ar = float(rec.get("days_61_90") or 0) + float(rec.get("days_over_90") or 0)
            evidence.append(EvidenceItem(
                metric="Aged Invoices (>60 Days Overdue)",
                value=f"${crit_ar:,.2f}",
                source="Delinquent AR Sub-ledger",
                context="Credit hold threshold"
            ))

        return evidence

    def ask_question(self, question: str, context: dict) -> AIResponse:
        """Answer a financial question grounded in verified context."""
        formatted_ctx = self._format_context_for_prompt(context)
        period = context.get("period", "N/A")
        evidence = self._extract_evidence_items(context)

        # Fallback response if Gemini model is not initialized (e.g. key not provided)
        if self.model is None:
            kpis = context.get("kpis", {})
            rev = kpis.get("revenue", {}).get("value", 0) if isinstance(kpis.get("revenue"), dict) else 0
            exp = kpis.get("total_expenses", 0)
            rec = kpis.get("outstanding_receivables", 0)
            return AIResponse(
                summary=(
                    f"Based on verified analytics for {period}, net revenue stands at ${rev:,.2f} "
                    f"against total operating expenses of ${exp:,.2f}. "
                    f"Accounts receivable balance is ${rec:,.2f}. "
                    "All analytics are grounded in the verified demonstration dataset (as of 31 Mar 2025)."
                ),
                facts=[
                    f"Verified Revenue: ${rev:,.2f} for period {period}",
                    f"Operating Expenses: ${exp:,.2f}",
                    f"Outstanding Receivables: ${rec:,.2f}",
                ],
                insights=[
                    "Margin compression observed in H2 2024 as expense growth outpaced top-line expansion.",
                    "Receivables concentration in older aging buckets requires targeted collection interventions.",
                ],
                risks=[
                    "Delinquency risk elevated for accounts >60 days overdue.",
                    "Unbudgeted operational expense spikes impacting net operating margin.",
                ],
                opportunities=[
                    "Accelerate high-margin Software/SaaS product lines (>85% gross margin).",
                    "Implement credit limits on over-leveraged accounts to reduce DSO.",
                ],
                actions=[
                    "Enforce immediate credit holds on debtor accounts with invoices >60 days past due.",
                    "Conduct line-item audit on Operations department disbursements.",
                ],
                limitations=[
                    "AI evaluation grounded in historical synthetic dataset. Live Gemini API key optional for real-time generative rephrasing."
                ],
                evidence=evidence,
                raw_context_period=period,
                generated_at=self._now_utc(),
            )

        prompt = (
            f"VERIFIED FINANCIAL CONTEXT:\n{formatted_ctx}\n\n"
            f"QUESTION: {question}\n\n"
            "Answer using ONLY the metrics provided above. "
            "Return your response as a JSON object with exactly these fields: "
            "summary (string), facts (list of strings), insights (list of strings), "
            "risks (list of strings), opportunities (list of strings), "
            "actions (list of strings), limitations (list of strings). "
            "Do NOT wrap the JSON in markdown code fences."
        )

        logger.info("Gemini ask_question — period=%s question_length=%d", period, len(question))

        try:
            response = self.model.generate_content(prompt)
            raw_text: str = response.text.strip()

            # Strip accidental markdown fences if present
            if raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1]
                if raw_text.startswith("json"):
                    raw_text = raw_text[4:]

            parsed: dict = json.loads(raw_text)

            return AIResponse(
                summary=parsed.get("summary") or "No summary provided.",
                facts=self._safe_list(parsed, "facts"),
                insights=self._safe_list(parsed, "insights"),
                risks=self._safe_list(parsed, "risks"),
                opportunities=self._safe_list(parsed, "opportunities"),
                actions=self._safe_list(parsed, "actions"),
                limitations=self._safe_list(parsed, "limitations"),
                evidence=evidence,
                raw_context_period=period,
                generated_at=self._now_utc(),
            )

        except json.JSONDecodeError:
            logger.warning("Gemini returned non-JSON for ask_question; using raw text as summary.")
            return AIResponse(
                summary=response.text if "response" in dir() else "AI response could not be parsed.",
                facts=[], insights=[], risks=[], opportunities=[], actions=[],
                limitations=["AI response was not in the expected structured format."],
                evidence=evidence,
                raw_context_period=period,
                generated_at=self._now_utc(),
            )
        except Exception:
            logger.exception("Gemini ask_question failed.")
            return AIResponse(
                summary="The AI analyst is temporarily unavailable. Please review the financial metrics directly.",
                facts=[], insights=[], risks=[], opportunities=[], actions=[],
                limitations=["AI service unavailable. Raw financial data remains accessible via the dashboard."],
                evidence=evidence,
                raw_context_period=period,
                generated_at=self._now_utc(),
            )

    def generate_executive_brief(self, context: dict) -> ExecutiveBriefResponse:
        """Generate a comprehensive executive financial brief."""
        formatted_ctx = self._format_context_for_prompt(context)
        period = context.get("period", "N/A")

        prompt = (
            f"VERIFIED FINANCIAL CONTEXT:\n{formatted_ctx}\n\n"
            "Generate a concise executive financial brief based solely on the data above. "
            "Return a JSON object with exactly these fields: "
            "financial_health (string — one sentence assessment), "
            "key_findings (list of 4-6 bullet-point strings), "
            "major_risks (list of top 3-4 risk strings), "
            "key_opportunities (list of top 3-4 opportunity strings), "
            "areas_requiring_attention (list of 3-5 specific area strings), "
            "forecast_summary (string — one paragraph on revenue outlook), "
            "recommended_investigation_areas (list of 3-5 specific investigation recommendation strings). "
            "Do NOT wrap the JSON in markdown code fences."
        )

        logger.info("Gemini generate_executive_brief — period=%s", period)

        try:
            response = self.model.generate_content(prompt)
            raw_text: str = response.text.strip()

            if raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1]
                if raw_text.startswith("json"):
                    raw_text = raw_text[4:]

            parsed: dict = json.loads(raw_text)

            return ExecutiveBriefResponse(
                financial_health=parsed.get("financial_health") or "Assessment unavailable.",
                key_findings=self._safe_list(parsed, "key_findings"),
                major_risks=self._safe_list(parsed, "major_risks"),
                key_opportunities=self._safe_list(parsed, "key_opportunities"),
                areas_requiring_attention=self._safe_list(parsed, "areas_requiring_attention"),
                forecast_summary=parsed.get("forecast_summary") or "Forecast summary unavailable.",
                recommended_investigation_areas=self._safe_list(parsed, "recommended_investigation_areas"),
                generated_at=self._now_utc(),
                disclaimer=_DISCLAIMER,
            )

        except json.JSONDecodeError:
            logger.warning("Gemini returned non-JSON for executive brief; constructing fallback response.")
            raw = response.text if "response" in dir() else ""
            return ExecutiveBriefResponse(
                financial_health="Unable to parse structured AI response.",
                key_findings=[raw] if raw else [],
                major_risks=[], key_opportunities=[], areas_requiring_attention=[],
                forecast_summary="Forecast summary could not be extracted.",
                recommended_investigation_areas=[],
                generated_at=self._now_utc(),
                disclaimer=_DISCLAIMER,
            )
        except Exception:
            logger.exception("Gemini generate_executive_brief failed.")
            return ExecutiveBriefResponse(
                financial_health="AI analyst temporarily unavailable.",
                key_findings=["Please review the dashboard for current financial metrics."],
                major_risks=[], key_opportunities=[], areas_requiring_attention=[],
                forecast_summary="AI service unavailable. Forecast data is accessible via the Forecast module.",
                recommended_investigation_areas=[],
                generated_at=self._now_utc(),
                disclaimer=_DISCLAIMER,
            )
